import { useMemo, useState } from 'react'
import { formatINR } from '@storefront/lib/currency'
import { useDataset } from '../lib/datasetContext'
import { checkIntegrity } from '../lib/metrics'
import {
  DASHBOARD_KEYS,
  STOREFRONT_KEYS,
  keyBytes,
  keyExists,
  readOrders,
  readReviews,
  readSubscribers,
} from '../lib/storage'
import { flattenReviews } from '../lib/analysis'
import { formatCount, pluralise } from '../lib/format'
import { downloadFile, stampedName, toCsv } from '../lib/csv'
import { Button } from '../components/ui/Controls'
import { Card, CardHeader, Chip } from '../components/ui/Card'
import { DownloadIcon } from '../components/ui/Icons'
import { useToast } from '../components/ui/Toast'

const bytes = (value: number) => (value < 1024 ? `${value} B` : `${(value / 1024).toFixed(1)} KB`)

export default function DataPage() {
  const { mode, orders, reviews, subscribers, rejected, user, cartLines, wishlist, demoPresent, seedDemo, clearDemo, now } =
    useDataset()
  const notify = useToast()
  const [confirmClear, setConfirmClear] = useState(false)

  const issues = useMemo(() => checkIntegrity(orders), [orders])

  const rows = useMemo(
    () => [
      { key: STOREFRONT_KEYS.orders, label: 'Orders', records: readOrders(STOREFRONT_KEYS.orders).value.length },
      {
        key: STOREFRONT_KEYS.reviews,
        label: 'Reviews',
        records: flattenReviews(readReviews(STOREFRONT_KEYS.reviews).value).length,
      },
      {
        key: STOREFRONT_KEYS.subscribers,
        label: 'Newsletter subscribers',
        records: readSubscribers(STOREFRONT_KEYS.subscribers).value.length,
      },
      { key: STOREFRONT_KEYS.cart, label: 'Open cart lines', records: cartLines },
      { key: STOREFRONT_KEYS.wishlist, label: 'Wishlist items', records: wishlist.length },
      { key: STOREFRONT_KEYS.user, label: 'Signed-in demo account', records: user ? 1 : 0 },
      {
        key: DASHBOARD_KEYS.demoOrders,
        label: 'Demo orders (this dashboard)',
        records: readOrders(DASHBOARD_KEYS.demoOrders).value.length,
      },
      {
        key: DASHBOARD_KEYS.demoReviews,
        label: 'Demo reviews (this dashboard)',
        records: flattenReviews(readReviews(DASHBOARD_KEYS.demoReviews).value).length,
      },
      {
        key: DASHBOARD_KEYS.demoSubscribers,
        label: 'Demo subscribers (this dashboard)',
        records: readSubscribers(DASHBOARD_KEYS.demoSubscribers).value.length,
      },
      { key: DASHBOARD_KEYS.fulfilment, label: 'Fulfilment stages (this dashboard)', records: null },
      { key: DASHBOARD_KEYS.mode, label: 'Live/demo preference', records: null },
    ],
    [cartLines, wishlist.length, user],
  )

  const exportJson = () => {
    const payload = {
      exportedAt: now.toISOString(),
      dataset: mode,
      note:
        mode === 'demo'
          ? 'SIMULATED DATA — generated by the dashboard, not real sales.'
          : 'Read from this browser’s localStorage. Orders exist only on the device that placed them.',
      orders,
      reviews,
      subscribers,
    }
    downloadFile(stampedName(`${mode}-export`, now, 'json'), JSON.stringify(payload, null, 2), 'application/json')
    notify('Export downloaded')
  }

  return (
    <div className="flex flex-col gap-3 p-3">
      <Card className="p-5">
        <h2 className="text-sm font-bold uppercase tracking-wider text-ink">Where these numbers come from</h2>
        <div className="mt-3 flex flex-col gap-3 text-sm text-body">
          <p>
            Elegant Sip has no backend yet. Orders, reviews and newsletter sign-ups are written by the
            storefront to <strong>localStorage</strong>, which a browser keeps <strong>per origin</strong> —
            per scheme, host and port. This dashboard is reading:
          </p>
          <p className="rounded-md border border-ink/10 bg-sunken px-3 py-2 font-mono text-xs text-ink">
            {window.location.origin}
          </p>
          <p>
            So it sees the storefront's real orders only when the shop is served from that same origin —
            for example both under <code>http://localhost/</code> on XAMPP. Two Vite dev servers on
            different ports each keep their own separate storage, and nothing is shared between devices
            or browsers. That is a limitation of having no server, not a bug in this page.
          </p>
        </div>
      </Card>

      <Card>
        <CardHeader
          title="Storage keys"
          subtitle="Everything the two apps keep in this browser"
          actions={
            <Button onClick={exportJson}>
              <span className="h-4 w-4">
                <DownloadIcon />
              </span>
              Export current dataset
            </Button>
          }
        />
        <div className="overflow-x-auto">
          <table className="w-full min-w-[40rem] border-collapse text-left text-sm">
            <thead>
              <tr className="text-xs uppercase tracking-wider text-muted">
                <th scope="col" className="px-5 py-2.5 font-semibold">Key</th>
                <th scope="col" className="px-3 py-2.5 font-semibold">Holds</th>
                <th scope="col" className="px-3 py-2.5 text-right font-semibold">Records</th>
                <th scope="col" className="px-5 py-2.5 text-right font-semibold">Size</th>
              </tr>
            </thead>
            <tbody>
              {rows.map((row) => (
                <tr key={row.key} className="border-t border-ink/5">
                  <td className="px-5 py-2.5 font-mono text-xs text-ink">{row.key}</td>
                  <td className="px-3 py-2.5 text-body">{row.label}</td>
                  <td className="tnum px-3 py-2.5 text-right text-body">
                    {row.records === null ? '—' : formatCount(row.records)}
                  </td>
                  <td className="tnum px-5 py-2.5 text-right text-body">
                    {keyExists(row.key) ? bytes(keyBytes(row.key)) : <span className="text-muted">not set</span>}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
        {(rejected.orders > 0 || rejected.reviews > 0 || rejected.subscribers > 0) && (
          <p className="border-t border-ink/10 px-5 py-3 text-xs text-body">
            Rejected on read as malformed or duplicated: {formatCount(rejected.orders)} order records,{' '}
            {formatCount(rejected.reviews)} reviews, {formatCount(rejected.subscribers)} subscriber entries.
            They are excluded from every figure in this dashboard.
          </p>
        )}
      </Card>

      <Card>
        <CardHeader
          title="Order integrity"
          subtitle="Each stored total re-derived from its line items using the storefront's own pricing"
        />
        {issues.length === 0 ? (
          <p className="px-5 py-4 text-sm text-body">
            All {pluralise(orders.length, 'order')} agree with the current pricing rules — 5% GST on goods and
            shipping, free standard shipping over {formatINR(4000)}.
          </p>
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full min-w-[32rem] border-collapse text-left text-sm">
              <thead>
                <tr className="text-xs uppercase tracking-wider text-muted">
                  <th scope="col" className="px-5 py-2.5 font-semibold">Order</th>
                  <th scope="col" className="px-3 py-2.5 text-right font-semibold">Stored</th>
                  <th scope="col" className="px-5 py-2.5 text-right font-semibold">Re-derived</th>
                </tr>
              </thead>
              <tbody>
                {issues.map((issue) => (
                  <tr key={issue.number} className="border-t border-ink/5">
                    <td className="tnum px-5 py-2.5 font-semibold text-ink">{issue.number}</td>
                    <td className="tnum px-3 py-2.5 text-right text-body">{formatINR(issue.storedTotal)}</td>
                    <td className="tnum px-5 py-2.5 text-right text-body">{formatINR(issue.expectedTotal)}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </Card>

      <Card className="p-5">
        <div className="flex flex-wrap items-start justify-between gap-3">
          <div className="min-w-0">
            <h2 className="text-sm font-bold uppercase tracking-wider text-ink">Demo dataset</h2>
            <p className="mt-1 max-w-2xl text-sm text-body">
              90 days of simulated trade, written to the dashboard's own keys — never to the storefront's.
              Order numbers start <code>ES-DEMO-</code>, all addresses use example.com, and every total is
              computed with the real pricing rules so the arithmetic behaves like a genuine order.
            </p>
          </div>
          <Chip tone={demoPresent ? 'accent' : 'neutral'}>{demoPresent ? 'Loaded' : 'Not loaded'}</Chip>
        </div>

        <div className="mt-4 flex flex-wrap items-center gap-2">
          <Button
            variant="primary"
            onClick={() => {
              const ok = seedDemo()
              notify(ok ? 'Demo dataset generated' : 'Storage refused the write — nothing was saved', ok ? 'ok' : 'error')
            }}
          >
            {demoPresent ? 'Regenerate demo data' : 'Load demo data'}
          </Button>
          {demoPresent &&
            (confirmClear ? (
              <>
                <span className="text-xs text-critical">Delete the demo dataset?</span>
                <Button
                  variant="danger"
                  onClick={() => {
                    clearDemo()
                    setConfirmClear(false)
                    notify('Demo dataset cleared')
                  }}
                >
                  Yes, clear it
                </Button>
                <Button variant="ghost" onClick={() => setConfirmClear(false)}>
                  Cancel
                </Button>
              </>
            ) : (
              <Button onClick={() => setConfirmClear(true)}>Clear demo data</Button>
            ))}
          <Button
            onClick={() => {
              downloadFile(
                stampedName('orders', now),
                toCsv(
                  ['Order', 'Date', 'Customer', 'Email', 'City', 'Total'],
                  orders.map((order) => [order.number, order.date, order.name, order.email, order.city, order.total]),
                ),
              )
              notify('Orders CSV downloaded')
            }}
            disabled={orders.length === 0}
          >
            Orders CSV
          </Button>
        </div>
      </Card>

      <Card className="p-5">
        <h2 className="text-sm font-bold uppercase tracking-wider text-ink">What this dashboard cannot do</h2>
        <ul className="mt-3 flex list-disc flex-col gap-1.5 pl-5 text-sm text-body">
          <li>Change prices, stock or product status — those live in the storefront's source and ship with a build.</li>
          <li>Notify a customer. Fulfilment stages and review deletions are local records; no email is sent.</li>
          <li>See orders from another device, browser or origin. There is no server to collect them.</li>
          <li>Report stock on hand. Catalogue lot sizes are static and never decrement as orders are placed.</li>
          <li>Verify a payment. The storefront checkout is a simulation and says so on the page.</li>
        </ul>
      </Card>
    </div>
  )
}
