import { useMemo, useState } from 'react'
import { formatINR } from '@storefront/lib/currency'
import { useDataset } from '../lib/datasetContext'
import { checkIntegrity } from '../lib/metrics'
import {
  DASHBOARD_KEYS,
  STOREFRONT_KEYS,
  keyBytes,
  keyExists,
  readOrders,
  readReviews,
  readSubscribers,
} from '../lib/storage'
import { flattenReviews } from '../lib/analysis'
import { formatCount, formatDate, formatDateTime, pluralise } from '../lib/format'
import { downloadFile, stampedName, toCsv } from '../lib/csv'
import { Button, SegmentedControl } from '../components/ui/Controls'
import { Card, CardHeader, Chip } from '../components/ui/Card'
import { TypeToConfirm } from '../components/ui/TypeToConfirm'
import { DownloadIcon, RefreshIcon } from '../components/ui/Icons'
import { useToast } from '../components/ui/Toast'

const bytes = (value: number) => (value < 1024 ? `${value} B` : `${(value / 1024).toFixed(1)} KB`)

export default function SettingsPage() {
  const {
    mode,
    setMode,
    refresh,
    orders,
    reviews,
    subscribers,
    rejected,
    user,
    cartLines,
    wishlist,
    demoPresent,
    seedDemo,
    clearDemo,
    ops,
    reseedOps,
    now,
  } = useDataset()
  const notify = useToast()
  const [confirming, setConfirming] = useState<'demo' | 'ops' | null>(null)

  const issues = useMemo(() => checkIntegrity(orders), [orders])

  const rows = useMemo(
    () => [
      { key: STOREFRONT_KEYS.orders, label: 'Orders', records: readOrders(STOREFRONT_KEYS.orders).value.length },
      {
        key: STOREFRONT_KEYS.reviews,
        label: 'Reviews',
        records: flattenReviews(readReviews(STOREFRONT_KEYS.reviews).value).length,
      },
      {
        key: STOREFRONT_KEYS.subscribers,
        label: 'Newsletter subscribers',
        records: readSubscribers(STOREFRONT_KEYS.subscribers).value.length,
      },
      { key: STOREFRONT_KEYS.cart, label: 'Open cart lines', records: cartLines },
      { key: STOREFRONT_KEYS.wishlist, label: 'Wishlist items', records: wishlist.length },
      { key: STOREFRONT_KEYS.user, label: 'Signed-in demo account', records: user ? 1 : 0 },
      {
        key: DASHBOARD_KEYS.demoOrders,
        label: 'Demo orders (this dashboard)',
        records: readOrders(DASHBOARD_KEYS.demoOrders).value.length,
      },
      {
        key: DASHBOARD_KEYS.demoReviews,
        label: 'Demo reviews (this dashboard)',
        records: flattenReviews(readReviews(DASHBOARD_KEYS.demoReviews).value).length,
      },
      {
        key: DASHBOARD_KEYS.demoSubscribers,
        label: 'Demo subscribers (this dashboard)',
        records: readSubscribers(DASHBOARD_KEYS.demoSubscribers).value.length,
      },
      { key: DASHBOARD_KEYS.ops, label: 'SKUs, trade prices and lots (this dashboard)', records: ops.lots.length },
      { key: DASHBOARD_KEYS.fulfilment, label: 'Fulfilment stages (this dashboard)', records: null },
      { key: DASHBOARD_KEYS.preferences, label: 'Row density, collapsed rail', records: null },
      { key: DASHBOARD_KEYS.mode, label: 'Live/demo preference', records: null },
    ],
    [cartLines, wishlist.length, user, ops.lots.length],
  )

  const exportJson = () => {
    const payload = {
      exportedAt: now.toISOString(),
      dataset: mode,
      note:
        mode === 'demo'
          ? 'SIMULATED DATA – generated by the dashboard, not real sales.'
          : 'Read from this browser’s localStorage. Orders exist only on the device that placed them.',
      orders,
      reviews,
      subscribers,
      operations: ops,
    }
    downloadFile(stampedName(`${mode}-export`, now, 'json'), JSON.stringify(payload, null, 2), 'application/json')
    notify('Export downloaded')
  }

  return (
    <div className="flex flex-col gap-4 p-4">
      <Card>
        <CardHeader
          title="Dataset"
          subtitle="Which numbers every screen in this dashboard is showing"
          actions={
            <Button onClick={refresh} title={`Last read ${formatDateTime(now.toISOString())}`}>
              <span className="h-3.5 w-3.5">
                <RefreshIcon />
              </span>
              Refresh
            </Button>
          }
        />
        <div className="flex flex-wrap items-center gap-2 px-3 py-2.5">
          <SegmentedControl
            label="Dataset"
            value={mode}
            onChange={setMode}
            segments={[
              { id: 'live', label: 'Live data' },
              { id: 'demo', label: demoPresent ? 'Demo data' : 'Demo (not loaded)' },
            ]}
          />
          <p className="text-sm text-muted">Last read {formatDateTime(now.toISOString())}.</p>
        </div>
      </Card>

      <Card className="px-3 py-2.5">
        <h2 className="text-xs font-semibold uppercase tracking-wider text-muted">
          Where these numbers come from
        </h2>
        <div className="mt-1.5 flex flex-col gap-2 text-sm text-body">
          <p>
            Elegant Sip has no backend yet. Orders, reviews and newsletter sign-ups are written by the
            storefront to <strong>localStorage</strong>, which a browser keeps <strong>per origin</strong>
            per scheme, host and port. This dashboard is reading:
          </p>
          <p className="rounded-sm neu-raised-sm bg-sunken px-2 py-1.5 font-mono text-xs text-ink">
            {window.location.origin}
          </p>
          <p>
            So it sees the storefront's real orders only when the shop is served from that same origin
            for example both under <code>http://localhost/</code> on XAMPP. Two Vite dev servers on
            different ports each keep their own separate storage, and nothing is shared between devices
            or browsers. That is a limitation of having no server, not a bug in this page.
          </p>
        </div>
      </Card>

      <Card>
        <CardHeader
          title="Operations overlay"
          subtitle="SKUs, tea types, trade prices, minimums and lots"
          actions={<Chip tone="accent">{pluralise(ops.lots.length, 'lot')}</Chip>}
        />
        <div className="flex flex-col gap-2 px-3 py-2.5 text-sm text-body">
          <p>
            The storefront's catalogue has no SKU, no weight as a number, no trade price and no concept of
            a lot – a shop does not need them and a back office cannot work without them. Rather than fork
            the catalogue, this dashboard keeps those fields in its own key and joins them by product id.
          </p>
          <p>
            <strong className="font-semibold text-ink">They are this office's records, not the shop's.</strong>{' '}
            Seeded on {formatDate(ops.seededAt)} from the catalogue itself: SKUs built from product ids and
            sizes, trade prices at 60% of retail, and lots that split each variant's published stock in two
            so the packs held for a SKU summed to what the shop publishes, until someone edited them here.
          </p>
          {confirming === 'ops' ? (
            <TypeToConfirm
              phrase="reseed"
              label="Reseed the overlay"
              consequence="Every trade price, minimum, lot count and write-off you have entered is replaced with freshly derived values. This cannot be undone."
              onCancel={() => setConfirming(null)}
              onConfirm={() => {
                const ok = reseedOps()
                setConfirming(null)
                notify(ok ? 'Overlay reseeded from the catalogue' : 'Storage refused the write', ok ? 'ok' : 'error')
              }}
            />
          ) : (
            <div>
              <Button variant="danger" onClick={() => setConfirming('ops')}>
                Reseed from catalogue
              </Button>
            </div>
          )}
        </div>
      </Card>

      <Card>
        <CardHeader
          title="Storage keys"
          subtitle="Everything the two apps keep in this browser"
          actions={
            <Button onClick={exportJson}>
              <span className="h-3.5 w-3.5">
                <DownloadIcon />
              </span>
              Export dataset
            </Button>
          }
        />
        <div className="overflow-x-auto">
          <table className="w-full min-w-[40rem] border-collapse text-left text-sm">
            <thead>
              <tr className="bg-sunken text-xs uppercase tracking-wider text-muted">
                <th scope="col" className="px-3 py-1.5 font-semibold">Key</th>
                <th scope="col" className="px-3 py-1.5 font-semibold">Holds</th>
                <th scope="col" className="px-3 py-1.5 text-right font-semibold">Records</th>
                <th scope="col" className="px-3 py-1.5 text-right font-semibold">Size</th>
              </tr>
            </thead>
            <tbody>
              {rows.map((row) => (
                <tr key={row.key} className="h-8 border-t border-line">
                  <td className="px-3 font-mono text-xs text-ink">{row.key}</td>
                  <td className="px-3 text-body">{row.label}</td>
                  <td className="px-3 text-right text-body">
                    {row.records === null ? '' : formatCount(row.records)}
                  </td>
                  <td className="px-3 text-right text-body">
                    {keyExists(row.key) ? bytes(keyBytes(row.key)) : <span className="text-muted">not set</span>}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
        {(rejected.orders > 0 || rejected.reviews > 0 || rejected.subscribers > 0) && (
          <p className="border-t border-line px-3 py-2 text-xs text-body">
            Rejected on read as malformed or duplicated: {formatCount(rejected.orders)} order records,{' '}
            {formatCount(rejected.reviews)} reviews, {formatCount(rejected.subscribers)} subscriber entries.
            They are excluded from every figure in this dashboard.
          </p>
        )}
      </Card>

      <Card>
        <CardHeader
          title="Order integrity"
          subtitle="Each stored total re-derived from its line items using the storefront's own pricing"
        />
        {issues.length === 0 ? (
          <p className="px-3 py-2.5 text-sm text-body">
            All {pluralise(orders.length, 'order')} agree with the current pricing rules  5% GST on goods and
            shipping, free standard shipping over {formatINR(4000)}.
          </p>
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full min-w-[32rem] border-collapse text-left text-sm">
              <thead>
                <tr className="bg-sunken text-xs uppercase tracking-wider text-muted">
                  <th scope="col" className="px-3 py-1.5 font-semibold">Order</th>
                  <th scope="col" className="px-3 py-1.5 text-right font-semibold">Stored</th>
                  <th scope="col" className="px-3 py-1.5 text-right font-semibold">Re-derived</th>
                </tr>
              </thead>
              <tbody>
                {issues.map((issue) => (
                  <tr key={issue.number} className="h-8 border-t border-line">
                    <td className="px-3 font-semibold text-ink">{issue.number}</td>
                    <td className="px-3 text-right text-body">{formatINR(issue.storedTotal)}</td>
                    <td className="px-3 text-right text-body">{formatINR(issue.expectedTotal)}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </Card>

      <Card>
        <CardHeader
          title="Demo dataset"
          subtitle="90 days of simulated trade, written to the dashboard's own keys – never the storefront's"
          actions={<Chip tone={demoPresent ? 'accent' : 'neutral'}>{demoPresent ? 'Loaded' : 'Not loaded'}</Chip>}
        />
        <div className="flex flex-col gap-2 px-3 py-2.5">
          <p className="text-sm text-body">
            Order numbers start <code>ES-DEMO-</code>, all addresses use example.com, and every total is
            computed with the real pricing rules so the arithmetic behaves like a genuine order.
          </p>
          <div className="flex flex-wrap items-center gap-2">
            <Button
              variant="primary"
              onClick={() => {
                const ok = seedDemo()
                notify(ok ? 'Demo dataset generated' : 'Storage refused the write – nothing was saved', ok ? 'ok' : 'error')
              }}
            >
              {demoPresent ? 'Regenerate demo data' : 'Load demo data'}
            </Button>
            {demoPresent && confirming !== 'demo' && (
              <Button onClick={() => setConfirming('demo')}>Clear demo data</Button>
            )}
            <Button
              onClick={() => {
                downloadFile(
                  stampedName('orders', now),
                  toCsv(
                    ['Order', 'Date', 'Customer', 'Email', 'City', 'Total'],
                    orders.map((order) => [order.number, order.date, order.name, order.email, order.city, order.total]),
                  ),
                )
                notify('Orders CSV downloaded')
              }}
              disabled={orders.length === 0}
            >
              Orders CSV
            </Button>
          </div>
          {confirming === 'demo' && (
            <TypeToConfirm
              phrase="erase"
              label="Clear demo data"
              consequence="Deletes the demo orders, reviews and subscribers. Regenerating afterwards builds a different 90 days – these exact figures do not come back."
              onCancel={() => setConfirming(null)}
              onConfirm={() => {
                clearDemo()
                setConfirming(null)
                notify('Demo dataset cleared')
              }}
            />
          )}
        </div>
      </Card>

      <Card className="px-3 py-2.5">
        <h2 className="text-xs font-semibold uppercase tracking-wider text-muted">
          What this dashboard cannot do
        </h2>
        <ul className="mt-1.5 flex list-disc flex-col gap-1 pl-5 text-sm text-body">
          <li>
            Change retail prices or product status – those live in the storefront's source and ship with a
            build. Trade prices, minimums and lots are this dashboard's own and are editable here.
          </li>
          <li>Notify a customer. Fulfilment stages and review deletions are local records; no email is sent.</li>
          <li>See orders from another device, browser or origin. There is no server to collect them.</li>
          <li>
            Decrement stock when an order is placed. Lots are adjusted by hand on the Inventory screen
            the storefront never tells this app that a sale happened.
          </li>
          <li>Verify a payment, process a refund, or see a subscription. The checkout is a simulation.</li>
        </ul>
      </Card>
    </div>
  )
}
